###
GET http://localhost:3000/calendarios

###
GET http://localhost:3000/calendarios/4

###
POST  http://localhost:3000/calendarios
Content-Type: application/json

{
    "dataHora": "2024-02-05",
    "tituloEvento": "reza",
    "descricao": "10",
    "comunidadeId": 1,
    "tipoEventoId": 10
}
###
PATCH   http://localhost:3000/calendarios/4
Content-Type: application/json

{
    "dataHora": "2024-02-05",
    "tituloEvento": "reza",
    "descricao": "10",
    "comunidadeId": 1,
    "tipoEventoId": 10,
    }
###
DELETE  http://localhost:3000/calendarios/3

###