###
GET http://localhost:3000/pessoas

###
GET http://localhost:3000/pessoas/2

###
POST  http://localhost:3000/pessoas
Content-Type: application/json

{
    "nome": "carlos",
    "cpf": "1234567887",
    "dataNascimento": "2020-02-05",
    "sexo": "reza",
     "comunidadeId":1
    }
###
PATCH   http://localhost:3000/pessoas/4
Content-Type: application/json

{
    "nome": "reza",
    "cpf": "r123781555",
    "dataNascimento": "2020-05-20",
    "sexo": "reza",
    "comunidadeId": 
    }
###
DELETE  http://localhost:3000/pessoas/2

###